/**
 * Interactive shell sessions: what a client asks for, and what it can be asked
 * back.
 *
 * The handshake is a discriminated union over `kind` rather than one wide
 * object, because the three kinds genuinely need different things. An ECS exec
 * needs a cluster and a container; an SSH to a colocated box needs neither, and
 * has no AWS profile at all. Spelling that as one object with everything
 * optional would push "which fields are set together" into every reader's head
 * and into no type.
 *
 * These schemas are parsed on the server at handshake time. A socket handshake
 * is the one place a client can put arbitrary JSON, so nothing here is trusted
 * until it has been through `execHandshakeSchema`.
 */
import { z } from "zod";

/** Terminal geometry, in character cells. */
const geometrySchema = z.object({
  cols: z.number().int().min(1).max(1000),
  rows: z.number().int().min(1).max(1000),
});

const sessionBaseSchema = geometrySchema.extend({
  /**
   * Generated by the client, one per terminal tab. It is the key a reattach
   * matches on, so it has to outlive the socket that created it.
   */
  sessionId: z.uuid(),
  /** True when this connection is resuming a tab whose socket dropped. */
  attach: z.boolean().default(false),
  /** Whether to write an asciicast of this session. */
  record: z.boolean().default(true),
});

/**
 * How to reach an SSH host.
 *
 * Four ways, because "can I get a TCP connection to port 22" has four different
 * answers depending on where the host lives: it is directly routable, it is
 * behind a jump host, it is an EC2 instance we can push an ephemeral key to, or
 * it is an EC2 instance with no public address that only SSM can reach.
 */
export const sshTransportSchema = z.discriminatedUnion("via", [
  z.object({
    via: z.literal("direct"),
    /** A literal hostname, or a `Host` alias to resolve through ~/.ssh/config. */
    host: z.string().min(1),
  }),
  z.object({
    via: z.literal("jump"),
    host: z.string().min(1),
    /** Outermost hop first, matching ssh's own `ProxyJump a,b,c` order. */
    jump: z.array(z.string().min(1)).min(1),
  }),
  z.object({
    via: z.literal("ec2-instance-connect"),
    profile: z.string(),
    region: z.string().min(1),
    instanceId: z.string().min(1),
    /** `ec2-user`, `ubuntu`, ... - the AMI decides, so the caller says. */
    osUser: z.string().min(1),
  }),
  z.object({
    via: z.literal("ssm-tunnel"),
    profile: z.string(),
    region: z.string().min(1),
    instanceId: z.string().min(1),
  }),
]);

export type SshTransport = z.infer<typeof sshTransportSchema>;

/**
 * Kubernetes names, fenced to what the API server would have accepted anyway.
 *
 * These regexes are not validation for its own sake: every one of these values
 * becomes part of an argument vector, and the fence is what stops a value being
 * read as a flag. `--kubeconfig=/etc/shadow` is a legal string and not a legal
 * pod name, and this is where the difference is enforced.
 */
const dnsLabel = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/;
const dnsSubdomain = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$/;

const kubeNameSchema = z.string().min(1).max(253).regex(dnsSubdomain, "Not a Kubernetes name.");
export const kubeLabelSchema = z.string().min(1).max(63).regex(dnsLabel, "Not a Kubernetes name.");

/**
 * A context NAME, never a kubeconfig path.
 *
 * The distinction is the whole point. A path crossing the wire would turn a
 * socket handshake into a server-side arbitrary-file read; a name is checked
 * against the contexts the server itself found in the kubeconfig it resolved,
 * so the value that reaches the command line is one we produced.
 *
 * Context names are user-chosen and routinely ugly - an EKS context is a whole
 * ARN - so this cannot be a DNS name. What it can insist on is no whitespace
 * and no leading `-`, which is the fence that matters here too.
 */
export const kubeContextSchema = z
  .string()
  .min(1)
  .max(253)
  .regex(/^[^-\s][^\s]*$/, "A context name cannot start with - or contain spaces.");

/**
 * What to run, and with which tool.
 *
 * Nested inside `kind: "kube"` rather than spread across three sibling kinds,
 * because all three are the same driver - resolve a binary, build argv, spawn,
 * pump stdio - and three kinds would mean three arms in every switch for one
 * seam. The fields genuinely differ per tool, so the union keeps "which fields
 * go together" in the type, exactly as `sshTransportSchema` does for SSH.
 */
export const kubeTargetSchema = z.discriminatedUnion("tool", [
  z.object({
    tool: z.literal("kubectl"),
    pod: kubeNameSchema,
    /** Absent means the pod's default container, as `kubectl exec` picks it. */
    container: kubeLabelSchema.optional(),
    /**
     * An argv, not a command line. There is no shell between here and the
     * container, so a single string would need a quoting parser, and a quoting
     * parser is a thing nobody wants to own.
     */
    command: z.array(z.string().min(1)).min(1).max(64).default(["/bin/sh"]),
  }),
  z.object({
    tool: z.literal("oc"),
    /** `rsh` is what an OpenShift user reaches for; `exec` is the same call. */
    mode: z.enum(["rsh", "exec"]).default("rsh"),
    pod: kubeNameSchema,
    container: kubeLabelSchema.optional(),
    command: z.array(z.string().min(1)).min(1).max(64).default(["/bin/sh"]),
  }),
  z.object({
    tool: z.literal("virtctl"),
    mode: z.enum(["ssh", "console"]),
    vm: kubeNameSchema,
    /** The guest login for `ssh`; `console` attaches to the serial port instead. */
    user: z
      .string()
      .min(1)
      .max(32)
      .regex(/^[a-z_][a-z0-9_-]*$/, "Not a login name.")
      .optional(),
  }),
]);

export type KubeTarget = z.infer<typeof kubeTargetSchema>;
export type KubeTool = KubeTarget["tool"];

export const execHandshakeSchema = z.discriminatedUnion("kind", [
  sessionBaseSchema.extend({
    kind: z.literal("ecs"),
    profile: z.string(),
    region: z.string().min(1),
    cluster: z.string().min(1),
    taskId: z.string().min(1),
    containerName: z.string().min(1),
    /** Whatever the image actually has; alpine has no /bin/bash. */
    command: z.string().min(1).default("/bin/sh"),
  }),
  sessionBaseSchema.extend({
    kind: z.literal("ssm"),
    profile: z.string(),
    region: z.string().min(1),
    instanceId: z.string().min(1),
    /** Defaults to SSM-SessionManagerRunShell on the AWS side when absent. */
    documentName: z.string().min(1).optional(),
    parameters: z.record(z.string(), z.array(z.string())).optional(),
    /** Try bash first, falling back to the default shell where it cannot run. */
    preferBash: z.boolean().optional(),
  }),
  sessionBaseSchema.extend({
    kind: z.literal("ssh"),
    transport: sshTransportSchema,
    /** Absent means "let ~/.ssh/config decide", then the local username. */
    user: z.string().min(1).optional(),
    port: z.number().int().min(1).max(65535).optional(),
    /** A one-shot command instead of an interactive login shell. */
    command: z.string().min(1).optional(),
  }),
  sessionBaseSchema.extend({
    kind: z.literal("kube"),
    context: kubeContextSchema,
    namespace: kubeLabelSchema,
    target: kubeTargetSchema,
  }),
]);

export type ExecHandshakeAuth = z.infer<typeof execHandshakeSchema>;
export type ExecKind = ExecHandshakeAuth["kind"];

/**
 * The kinds, once.
 *
 * The enum was being written out again wherever one was needed - most
 * dangerously in the remembered-tabs schema, where a kind it had not been told
 * about drops every remembered tab rather than the one it did not recognise.
 * `satisfies` is what keeps this list and the handshake union from drifting.
 */
export const EXEC_KINDS = ["ecs", "ssm", "ssh", "kube"] as const satisfies readonly ExecKind[];
export const execKindSchema = z.enum(EXEC_KINDS);

/**
 * Something the server needs from the person before it can continue.
 *
 * This exists because a host key we have never seen is a decision, not an
 * error, and answering it silently - in either direction - is the wrong move.
 * Trusting it silently is how you get a man-in-the-middle; refusing silently is
 * how you get a tool nobody can connect with.
 */
export const execPromptSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("hostkey"),
    promptId: z.string().min(1),
    host: z.string(),
    port: z.number().int(),
    /** `ssh-ed25519`, `ecdsa-sha2-nistp256`, ... */
    keyType: z.string(),
    fingerprintSha256: z.string(),
    /** Exactly what would be appended, so it can be read before it is written. */
    knownHostsLine: z.string(),
  }),
  z.object({
    kind: z.literal("passphrase"),
    promptId: z.string().min(1),
    keyPath: z.string(),
  }),
  z.object({
    kind: z.literal("password"),
    promptId: z.string().min(1),
    user: z.string(),
    host: z.string(),
  }),
  z.object({
    kind: z.literal("keyboard-interactive"),
    promptId: z.string().min(1),
    name: z.string(),
    instructions: z.string(),
    questions: z.array(z.object({ prompt: z.string(), echo: z.boolean() })),
  }),
]);

export type ExecPrompt = z.infer<typeof execPromptSchema>;

/**
 * The answer. `reject` is always available and is always the default the UI
 * focuses: a prompt that times out or whose tab closes counts as a refusal,
 * never as consent.
 */
export const execPromptResponseSchema = z.object({
  promptId: z.string().min(1),
  /** For a host key: trust it for this session only, or write known_hosts. */
  trust: z.enum(["once", "permanent", "reject"]).optional(),
  /** For a secret prompt. Never stored, never logged, never echoed back. */
  value: z.string().optional(),
  /** For keyboard-interactive, one answer per question, in order. */
  answers: z.array(z.string()).optional(),
  cancelled: z.boolean().default(false),
});

export type ExecPromptResponse = z.infer<typeof execPromptResponseSchema>;

/**
 * Stable error codes, so the UI can offer the right next step rather than
 * printing a sentence. Every one of these has a remediation the user can act
 * on, which is the bar for adding another.
 */
export type ExecErrorCode =
  | "BadHandshake"
  | "NoDriver"
  | "SessionGone"
  | "TooManySessions"
  | "SessionManagerPluginMissing"
  | "SessionManagerPluginFailed"
  | "ExecuteCommandDisabled"
  | "ExecAgentNotRunning"
  | "TargetNotConnected"
  | "InvalidInstanceId"
  | "AccessDenied"
  | "HostKeyChanged"
  | "HostKeyRejected"
  | "KnownHostsUnparseable"
  | "SshConfigUnsupported"
  | "AuthFailed"
  | "ConnectTimeout"
  | "InstanceConnectFailed"
  | "KubeBinaryMissing"
  | "KubeconfigMissing"
  | "KubeContextUnknown"
  | "KubeApiUnreachable"
  | "KubeAuthFailed"
  | "KubeForbidden"
  | "KubePodNotFound"
  | "KubeContainerNotFound"
  | "KubeVmNotRunning"
  | "KubeVirtUnavailable"
  | "Internal";

/** A live session, as the sessions list and the dock's tab strip see it. */
export interface ExecSessionSummary {
  readonly sessionId: string;
  readonly kind: ExecKind;
  /** Human-readable target: `cluster/task/container`, an instance id, a host. */
  readonly target: string;
  readonly profile: string | null;
  readonly region: string | null;
  readonly startedAt: string;
  readonly state: "starting" | "running" | "detached" | "closing" | "closed";
  readonly recordingPath: string | null;
}

/**
 * An instance you could open a shell on, and how.
 *
 * Joined from two APIs that each know half the story: DescribeInstances knows
 * the instance exists and whether it has an address, DescribeInstanceInformation
 * knows whether SSM can actually reach it. Neither answers "can I get a shell
 * here", which is the only question the picker is asking.
 */
export interface ExecInstanceTarget {
  readonly instanceId: string;
  /** The Name tag, which is what people actually recognise. */
  readonly name: string | null;
  readonly state: string;
  readonly privateIp: string | null;
  readonly publicIp: string | null;
  readonly availabilityZone: string | null;
  readonly platform: string | null;
  readonly instanceType: string | null;
  readonly vpcId: string | null;
  /** The EC2 key pair it was launched with, if any. */
  readonly keyName: string | null;
  /**
   * The login name this AMI ships with, read from the image name. A guess, but
   * a checked one, and the error when it is wrong says so.
   */
  readonly osUser: string;
  /** Registered with Session Manager and currently reachable. */
  readonly ssmManaged: boolean;
  readonly ssmPingStatus: string | null;
  readonly ssmAgentVersion: string | null;
  /**
   * What this instance can be reached by, best first. Empty means nothing here
   * will work, which is worth saying plainly rather than offering a button that
   * cannot succeed.
   */
  readonly reachableBy: ReadonlyArray<"ssm" | "ssh-public" | "ssh-ssm-tunnel">;
}

/**
 * What the new-session form collects.
 *
 * Separate from `execHandshakeSchema` on purpose: this is what a person types,
 * while the handshake is what the server is handed. A form field is a string
 * with a default and a friendly message; a handshake field is already resolved.
 * Collapsing the two would mean either a form that cannot have an empty field
 * or a handshake that has to tolerate one.
 */
export const ssmSessionFormSchema = z.object({
  kind: z.literal("ssm"),
  instanceId: z.string().min(1, "Pick an instance."),
});

export const sshSessionFormSchema = z.object({
  host: z.string().trim().min(1, "Enter a hostname, or a Host from your ~/.ssh/config."),
  /** Empty means "let ~/.ssh/config decide", then the local username. */
  user: z.string().trim().default(""),
  port: z.coerce.number().int().min(1, "Between 1 and 65535.").max(65535, "Between 1 and 65535."),
});

export type SshSessionFormInput = z.input<typeof sshSessionFormSchema>;
export type SshSessionFormValues = z.output<typeof sshSessionFormSchema>;

/**
 * The kube half of the same form.
 *
 * Separate from the handshake for the reason above, and here the gap is wider
 * than anywhere else: the handshake takes an argv, while a person types one
 * line and expects `/bin/sh` if they type nothing. Splitting that line is the
 * client's job, and it happens before the handshake rather than inside it.
 */
export const kubeExecFormSchema = z.object({
  tool: z.enum(["kubectl", "oc"]).default("kubectl"),
  context: z.string().trim().min(1, "Pick a context."),
  namespace: z.string().trim().min(1, "Pick a namespace."),
  pod: z.string().trim().min(1, "Enter a pod name."),
  /** Empty means the pod's default container. */
  container: z.string().trim().default(""),
  command: z.string().trim().default("/bin/sh"),
});

export const kubeSshFormSchema = z.object({
  context: z.string().trim().min(1, "Pick a context."),
  namespace: z.string().trim().min(1, "Pick a namespace."),
  vm: z.string().trim().min(1, "Enter a virtual machine name."),
  user: z.string().trim().min(1, "Enter the guest login to use."),
});

export type KubeExecFormInput = z.input<typeof kubeExecFormSchema>;
export type KubeExecFormValues = z.output<typeof kubeExecFormSchema>;
export type KubeSshFormInput = z.input<typeof kubeSshFormSchema>;
export type KubeSshFormValues = z.output<typeof kubeSshFormSchema>;
