/**
 * Interactive shell sessions: what a client asks for, and what it can be asked
 * back.
 *
 * The handshake is a discriminated union over `kind` rather than one wide
 * object, because the three kinds genuinely need different things. An ECS exec
 * needs a cluster and a container; an SSH to a colocated box needs neither, and
 * has no AWS profile at all. Spelling that as one object with everything
 * optional would push "which fields are set together" into every reader's head
 * and into no type.
 *
 * These schemas are parsed on the server at handshake time. A socket handshake
 * is the one place a client can put arbitrary JSON, so nothing here is trusted
 * until it has been through `execHandshakeSchema`.
 */
import { z } from "zod";

/** Terminal geometry, in character cells. */
const geometrySchema = z.object({
  cols: z.number().int().min(1).max(1000),
  rows: z.number().int().min(1).max(1000),
});

const sessionBaseSchema = geometrySchema.extend({
  /**
   * Generated by the client, one per terminal tab. It is the key a reattach
   * matches on, so it has to outlive the socket that created it.
   */
  sessionId: z.uuid(),
  /** True when this connection is resuming a tab whose socket dropped. */
  attach: z.boolean().default(false),
  /** Whether to write an asciicast of this session. */
  record: z.boolean().default(true),
});

/**
 * How to reach an SSH host.
 *
 * Four ways, because "can I get a TCP connection to port 22" has four different
 * answers depending on where the host lives: it is directly routable, it is
 * behind a jump host, it is an EC2 instance we can push an ephemeral key to, or
 * it is an EC2 instance with no public address that only SSM can reach.
 */
export const sshTransportSchema = z.discriminatedUnion("via", [
  z.object({
    via: z.literal("direct"),
    /** A literal hostname, or a `Host` alias to resolve through ~/.ssh/config. */
    host: z.string().min(1),
  }),
  z.object({
    via: z.literal("jump"),
    host: z.string().min(1),
    /** Outermost hop first, matching ssh's own `ProxyJump a,b,c` order. */
    jump: z.array(z.string().min(1)).min(1),
  }),
  z.object({
    via: z.literal("ec2-instance-connect"),
    profile: z.string(),
    region: z.string().min(1),
    instanceId: z.string().min(1),
    /** `ec2-user`, `ubuntu`, ... - the AMI decides, so the caller says. */
    osUser: z.string().min(1),
  }),
  z.object({
    via: z.literal("ssm-tunnel"),
    profile: z.string(),
    region: z.string().min(1),
    instanceId: z.string().min(1),
  }),
]);

export type SshTransport = z.infer<typeof sshTransportSchema>;

export const execHandshakeSchema = z.discriminatedUnion("kind", [
  sessionBaseSchema.extend({
    kind: z.literal("ecs"),
    profile: z.string(),
    region: z.string().min(1),
    cluster: z.string().min(1),
    taskId: z.string().min(1),
    containerName: z.string().min(1),
    /** Whatever the image actually has; alpine has no /bin/bash. */
    command: z.string().min(1).default("/bin/sh"),
  }),
  sessionBaseSchema.extend({
    kind: z.literal("ssm"),
    profile: z.string(),
    region: z.string().min(1),
    instanceId: z.string().min(1),
    /** Defaults to SSM-SessionManagerRunShell on the AWS side when absent. */
    documentName: z.string().min(1).optional(),
    parameters: z.record(z.string(), z.array(z.string())).optional(),
  }),
  sessionBaseSchema.extend({
    kind: z.literal("ssh"),
    transport: sshTransportSchema,
    /** Absent means "let ~/.ssh/config decide", then the local username. */
    user: z.string().min(1).optional(),
    port: z.number().int().min(1).max(65535).optional(),
    /** A one-shot command instead of an interactive login shell. */
    command: z.string().min(1).optional(),
  }),
]);

export type ExecHandshakeAuth = z.infer<typeof execHandshakeSchema>;
export type ExecKind = ExecHandshakeAuth["kind"];

/**
 * Something the server needs from the person before it can continue.
 *
 * This exists because a host key we have never seen is a decision, not an
 * error, and answering it silently - in either direction - is the wrong move.
 * Trusting it silently is how you get a man-in-the-middle; refusing silently is
 * how you get a tool nobody can connect with.
 */
export const execPromptSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("hostkey"),
    promptId: z.string().min(1),
    host: z.string(),
    port: z.number().int(),
    /** `ssh-ed25519`, `ecdsa-sha2-nistp256`, ... */
    keyType: z.string(),
    fingerprintSha256: z.string(),
    /** Exactly what would be appended, so it can be read before it is written. */
    knownHostsLine: z.string(),
  }),
  z.object({
    kind: z.literal("passphrase"),
    promptId: z.string().min(1),
    keyPath: z.string(),
  }),
  z.object({
    kind: z.literal("password"),
    promptId: z.string().min(1),
    user: z.string(),
    host: z.string(),
  }),
  z.object({
    kind: z.literal("keyboard-interactive"),
    promptId: z.string().min(1),
    name: z.string(),
    instructions: z.string(),
    questions: z.array(z.object({ prompt: z.string(), echo: z.boolean() })),
  }),
]);

export type ExecPrompt = z.infer<typeof execPromptSchema>;

/**
 * The answer. `reject` is always available and is always the default the UI
 * focuses: a prompt that times out or whose tab closes counts as a refusal,
 * never as consent.
 */
export const execPromptResponseSchema = z.object({
  promptId: z.string().min(1),
  /** For a host key: trust it for this session only, or write known_hosts. */
  trust: z.enum(["once", "permanent", "reject"]).optional(),
  /** For a secret prompt. Never stored, never logged, never echoed back. */
  value: z.string().optional(),
  /** For keyboard-interactive, one answer per question, in order. */
  answers: z.array(z.string()).optional(),
  cancelled: z.boolean().default(false),
});

export type ExecPromptResponse = z.infer<typeof execPromptResponseSchema>;

/**
 * Stable error codes, so the UI can offer the right next step rather than
 * printing a sentence. Every one of these has a remediation the user can act
 * on, which is the bar for adding another.
 */
export type ExecErrorCode =
  | "BadHandshake"
  | "NoDriver"
  | "TooManySessions"
  | "SessionManagerPluginMissing"
  | "SessionManagerPluginFailed"
  | "ExecuteCommandDisabled"
  | "ExecAgentNotRunning"
  | "TargetNotConnected"
  | "InvalidInstanceId"
  | "AccessDenied"
  | "HostKeyChanged"
  | "HostKeyRejected"
  | "KnownHostsUnparseable"
  | "SshConfigUnsupported"
  | "AuthFailed"
  | "ConnectTimeout"
  | "InstanceConnectFailed"
  | "Internal";

/** A live session, as the sessions list and the dock's tab strip see it. */
export interface ExecSessionSummary {
  readonly sessionId: string;
  readonly kind: ExecKind;
  /** Human-readable target: `cluster/task/container`, an instance id, a host. */
  readonly target: string;
  readonly profile: string | null;
  readonly region: string | null;
  readonly startedAt: string;
  readonly state: "starting" | "running" | "detached" | "closing" | "closed";
  readonly recordingPath: string | null;
}
